NAME: zi2zi_refactor
FOLDER: ./exps/01/
MODEL:
  type: Z2Z
  backbone:
    type: ResNet18
    out_dim: 512
    weights: /home/user/julianjuaner/research/pretrain/resnet18.pth
  decoder:
    type: SimpleUpsample
    stride: 32
  discriminator: 
    type: zi2zi
  embedding:
    type: SimpleEmbedding
    embedding_num: 195
    embedding_dim: 128

  loss:
    - type: TotalVar
      weight: 0.0
    - type: Constance
      weight: 15.0
    - type: Category
      weight: 1.0
    - type: L1
      weight: 100.0

  dropout: 0.0
  in_channels: 1
  out_channels: 1

DATA:
  preprocessor:
    - type: Rescale
      output_size: [256, 256]

  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  value_scale: 255

  train_data:
    type: FontImgDataset
    data_name: train
    mode: train
    root: '/home/user/julianjuaner/research/zi2zi/data/dir/'
    data_path:
        - '/home/user/julianjuaner/research/zi2zi/data/train_list.txt'
      
  eval_data:
    type: FontImgDataset
    data_name: val
    mode: evaluate
    root: '/home/user/julianjuaner/research/zi2zi/data/dir/'
    data_path:
      - '/home/user/julianjuaner/research/zi2zi/data/test_list.txt'

  test_data:
    type: FontImgDataset
    data_name: test
    mode: test
    root: '/home/user/julianjuaner/research/zi2zi/data/dir/'
    data_path:
      - '/home/user/julianjuaner/research/floor/data/test_list.txt'

EVALUATE:
  evaluators:
    - type: L1_distance

TRAIN:
  optimizer:
    type: AdamOptimizer
    lr: 0.001

  lr_scheduler:
    type: StepLR
    half_epoch: 10

  gen_lr_factor: 1.0
  dis_lr_factor: 2.0
  flip_label: True

  data_argumentation:
    - type: RandomRotation
      prob: 0.3
      angle: [-10, 10]
    - type: RandomScale
      scale: [0.8, 1.2]
      prob: 0.7
      hw_prob: 0.5
    - type: RandomCrop
      output_size: [256, 256]
    - type: RandomLineWidth
      prob: 0.2
      max_dilation_time: 3
      max_erode_time: 3
    - type: GaussianBlur
      prob: 0.3
      kernel_range: [3, 5, 7]

  max_epoch: 100
  ckpt_freq: 5
  eval_freq: 5
  resume: 0

  print_freq: 20 # iteration
  batch_size_per_gpu: 32

EVAL:
  epoch: -1